# Generated by Django 4.1.1 on 2022-09-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('geography', models.CharField(max_length=10000)),
                ('history', models.CharField(max_length=10000)),
                ('culture', models.CharField(max_length=10000)),
                ('language', models.CharField(max_length=10000)),
                ('infrastructure', models.CharField(max_length=10000)),
                ('tourist_spots', models.CharField(max_length=10000)),
            ],
        ),
    ]
